### ISSUE TITLE
Pin or harden unpdf dependency for Node 22 PDF support

### ISSUE THREAD

**Issue by oguzbilgic** [oguzbilgic/kern-ai#285]
## Problem
Fresh installs can resolve `unpdf` from the current semver range (`^1.4.0`) to newer versions such as `1.6.0`. Those newer versions/pdf.js paths can call newer JS APIs like `Promise.try`, which is unavailable on Node 22, causing the PDF tool to fail with:

`TypeError: Promise.try is not a function`

This is a runtime compatibility issue, not the native font/cairo dependency issue.

## Current finding
- Existing dev checkout has `unpdf@1.4.0` in lockfile and works on Node 22.
- kern-hub fresh install reports Node 22.x and `unpdf@1.6.0` pinned by kern-ai via the semver range.
- Node 22: `typeof Promise.try === undefined`.

## Plan
1. Immediate patch: change `package.json` dependency from `^1.4.0` to exact `1.4.0` and refresh lockfile.
2. Add/update Docker and install verification if needed to ensure fresh installs resolve `unpdf@1.4.0`.
3. Test PDF tool on Node 22 with a sample PDF.
4. Later: evaluate latest `unpdf` with upstream polyfills or Node 24 support before widening the range again.

## Acceptance criteria
- Fresh `npm install` resolves `unpdf@1.4.0` exactly.
- PDF tool no longer fails with `Promise.try is not a function` on Node 22.
- Changelog notes the compatibility pin.

**Comment by oguzbilgic** [comment]
## First production hit (2026-05-19, kern-imroz)

Confirmed same root cause in the wild. Ali sent Imroz a PDF in Telegram, agent crashed on extraction. Restarted twice — crashes within 5-12s every time.

**Environment:**
- kern-imroz (kern-ai v0.31.0, Node v22.22.1)
- unpdf resolved to current via `^1.4.0` range
- pdfjs.mjs MessageHandler calls `Promise.try` in multiple places (action handler, stream pull, stream cancel)

**Crash trace:**
```
TypeError: Promise.try is not a function
    at #t (file:///usr/lib/node_modules/kern-ai/node_modules/unpdf/dist/pdfjs.mjs:54:112364)
    at      file:///usr/lib/node_modules/kern-ai/node_modules/unpdf/dist/pdfjs.mjs:54:110186
Node.js v22.22.1
```

**Hard crash loop behavior:**
The crash is uncaught and exits the process before the Telegram message can be acked. On restart, the agent re-pulls the same PDF, crashes again. Result: agent stays permanently down on any operator-sent PDF until either (a) the unpdf path is fixed, or (b) the message is manually skipped via cursor advance.

**Suggested additions to the plan:**
- Catch/guard the PDF extraction path so a bad PDF cannot kill the process (defense in depth — even after pinning, a poisoned PDF shouldn't be able to brick an agent).
- Consider advancing Telegram cursor / dropping the offending message during boot recovery to break the loop.

**Comment by oguzbilgic** [comment]
Update 2026-06-11: upstream fixed this.

- `unpdf` 1.6.1 (2026-04-28) / 1.6.2 (2026-04-29) added a `Promise.try` polyfill in the bundled pdfjs, so the Node 22 crash from 1.6.0 is gone.
- Verified locally: `unpdf@1.6.2` text extraction works on Node v22.22.1.

So fresh installs resolving `^1.4.0` → 1.6.2 work again. No urgent pin needed, but we may still pin to an exact known-good version (e.g. `1.6.2`) defensively, since 1.6.0 showed upstream is willing to ship runtime-breaking changes in patch/minor releases.
